### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by AeroNotix** [jfacorro/clojerl#356] opened 2017-07-31 18:48 UTC
```
Compiling clojure.pprint...escript: exception error: bad argument
  in function  binary_to_term/1
     called as binary_to_term(<<131,80,0,5,39,116,120,156,237,125,109,115,227,
                                72,146,30,41,82,111,221,154,238,217,238,221,
                                139,139,185,181,163,125,23,51,225,27,175,186,
                                69,73,124,145,61,125,61,246,158,199,222,...>>)
  in call from clj_utils:core_from_binary/1 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_utils.erl, line 353)
  in call from clj_module:load/2 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_module.erl, line 395)
  in call from clj_module:ensure_loaded/2 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_module.erl, line 106)
  in call from clj_emitter:ast/2 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_emitter.erl, line 97)
  in call from clj_emitter:emit/1 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_emitter.erl, line 19)
  in call from clj_compiler:emit_eval_form/2 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_compiler.erl, line 300)
  in call from clj_reader:read_fold_loop/2 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_reader.erl, line 78)
  in call from clj_compiler:'-do_compile/3-fun-4-'/2 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_compiler.erl, line 245)
  in call from clj_module:with_context/1 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_module.erl, line 85)
  in call from clj_compiler:do_compile/3 (/home/xeno/dev/clojerl/_build/default/lib/clojerl/src/erl/clj_compiler.erl, line 255)
make[1]: *** [Makefile:93: /home/xeno/dev/clojerl/_build/default/lib/clojerl/ebin/clojure.pprint.beam] Error 127
===> Hook for compile failed!
```

**Comment by arpunk** [comment] 2017-07-31 19:09
What version of Erlang/rebar3 are you using? FWIW I'm using rebar3 3.4.2 and Erlang/OTP 20.0.2 and everything compiles fine.

**Comment by jfacorro** [comment] 2017-07-31 19:27
@AeroNotix Thank you for reporting this! As @arpunk mentioned, please let us know the Erlang/OTP and `rebar3` versions you are using so we can reproduce the problem.

**Comment by AeroNotix** [comment] 2017-07-31 20:56
rebar 3.0.0-beta-1 / R19

**Comment by jfacorro** [comment] 2017-07-31 22:54
@AeroNotix It's weird. Compiling `rebar3`'s `beta-1` tag needs Erlang/OTP 18.3, since running `./bootstrap` with 19.3 results in the following warnings and it fails to compile:
```
/Users/juan.facorro/dev/jfacorro/rebar3/_build/default/lib/erlware_commons/src/ec_file.erl:177: Warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
/Users/juan.facorro/dev/jfacorro/rebar3/_build/default/lib/erlware_commons/src/ec_file.erl:178: Warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
```
When I use this `rebar3` binary (compiled with OTP 18.3) but running 19.3 I get a different error when running `make`:
```
$ make
===> Verifying dependencies...
===> Compiling clojerl
Compiling clojure.core...done
Compiling clojure.stacktrace...done
Compiling clojure.walk...done
Compiling clojure.pprint...done
Compiling clojure.repl...done
Compiling clojure.set...done
Compiling clojure.data...done
Compiling clojure.xml...done
Compiling clojure.test-helper...done
Compiling clojure.main...done
Compiling clojure.zip...done
===> Missing artifact priv/clojerl.so
make: *** [Makefile:17: compile] Error 1
```
Could you try upgrading `rebar3` and trying with a newer version? If you don't want to compile `rebar3` from source you can get a compiled binary from [here](https://s3.amazonaws.com/rebar3/rebar3), this is what the builds in [Travis-CI](https://travis-ci.org/) use (`rebar 3.4.2`).

**Comment by AeroNotix** [comment] 2017-07-31 22:56
I run with erln8 so this is why the versions don't match between what I compiled rebar3 with compared to the version I am trying to build clojerl with. Will build a new version of rebar3 and see how it goes.

**Comment by jfacorro** [comment] 2017-08-05 22:56
@AeroNotix Did you get a chance to try this out?

**Comment by jfacorro** [comment] 2017-08-08 21:41
@AeroNotix I will close this issue for now, please let us know if you weren't able to build after using a newer `rebar3` version.

**Closed by jfacorro** 2017-08-08 21:41 UTC
